export type BuiltInLanguage = "en" | "zh";
export type LanguageMode = "browser" | BuiltInLanguage | `custom:${string}`;

export const BUILT_IN_LANGUAGE_OPTIONS: Array<{ value: LanguageMode; label: string }> = [
  { value: "browser", label: "Follow browser" },
  { value: "en", label: "English" },
  { value: "zh", label: "中文" }
];

export const EN_TRANSLATIONS = {
  "app.documentTitle": "ChatMap",
  "app.documentTitle.fullPage": "ChatMap Full Page",
  "app.kicker": "Conversation mind map",
  "app.subtitle.hasTurns": "Right-click a turn node to jump back to its source message.",
  "app.subtitle.noTurns": "No complete turns found yet.",
  "jump.heading.pending": "Jumping to source message",
  "jump.heading.success": "Jump complete",
  "jump.heading.error": "Could not jump to source message",
  "jump.inProgress": "Opening turn {number} in the conversation page…",
  "jump.succeeded": "Turn {number} was located in the conversation page.",
  "jump.failed": "The jump failed without returning a reason.",
  "jump.missingTurn": "This node is not linked to a captured conversation turn.",
  "jump.dismiss": "Dismiss message",
  "app.empty.title": "No map yet",
  "app.empty.hint": "Open a supported AI conversation with at least one complete answer.",
  "app.action.refresh": "Refresh",
  "app.action.refreshing": "Scanning...",
  "app.action.rebuild": "Rebuild",
  "app.action.refreshIndex": "Refresh Index",
  "app.action.scanning": "Scanning index...",
  "app.action.settings": "Settings",
  "app.action.debug": "Debug",
  "app.action.view": "View",
  "app.view.sidePanel": "Side Panel",
  "app.view.fullPage": "Full Page",
  "app.view.showFloat": "Show Float",
  "app.view.hideFloat": "Hide Float",
  "app.view.current": "Current",
  "app.confirm.deleteExpansion": "Delete this answer expansion? The original answer stays, but mini-map edits will be removed.",
  "app.confirm.reexpandAnswer": "Re-expand this answer with AI? This can overwrite existing mini-map edits.",
  "app.status.waiting": "Waiting for an AI conversation...",
  "app.status.cacheFailed": "Turns loaded, but IndexedDB caching failed.",
  "app.status.mappedVia": "{count} turns mapped via {source}",
  "app.status.loadedTurns": "{count} loaded turns mapped",
  "app.status.refreshAdded": "Refresh added {added} new turns; {total} total.",
  "app.status.refreshNoNew": "Refresh found no new turns; {total} total.",
  "app.status.refreshIndexAdded": "Index refresh added {added} available turns; {total} total.",
  "app.status.refreshIndexNoNew": "Index refresh found no new available turns; {total} total.",
  "app.status.refreshIndexReordered": "Index refreshed and reordered {total} turns from the conversation.",
  "app.status.refreshIndexOrderKept": "The scan covered {scanned} turns, but not enough of the {total} saved turns to safely reorder; the existing map was kept.",
  "app.status.refreshRecomputed": "ChatGPT was rescanned and its {total} turn nodes and layout were rebuilt.",
  "app.status.refreshScanFailed": "Conversation scan failed: {reason}. The existing map was kept.",
  "app.status.restoredConversation": "Restored the saved map for this conversation with {count} turns.",
  "app.status.switchReadingIndex": "Refreshing this conversation index before switching maps...",
  "app.status.switchCreated": "Created a map for this conversation with {count} turns.",
  "app.status.switchReadFailed": "Could not read this conversation, so the current map was kept.",
  "app.status.reading": "Reading newly loaded AI turns...",
  "app.status.rebuilding": "Recalculating the layout from saved turns...",
  "app.status.rebuilt": "Mind map rebuilt from {count} turns.",
  "app.status.rebuildNoTurns": "There are no saved turns to rebuild yet.",
  "app.status.refreshScanEmpty": "The page scan returned no turns; the saved graph was kept.",
  "app.status.openConversation": "Open a supported AI conversation tab, then refresh ChatMap.",
  "app.status.refreshingIndex": "Refreshing the available conversation index...",
  "app.status.refreshIndexFailed": "Index refresh could not reach the active conversation tab.",
  "app.status.noActiveTab": "No active supported AI conversation tab was found.",
  "app.status.floatEnabled": "Floating panel enabled",
  "app.status.floatDisabled": "Floating panel disabled",
  "app.status.floatFailed": "Could not reach the conversation tab for floating panel.",
  "app.status.layoutSet": "Layout set to {layout}",
  "debug.conversation": "Conversation",
  "debug.site": "Site",
  "debug.id": "ID",
  "debug.turns": "Turns",
  "debug.source": "Source",
  "debug.selectorTurns": "Selector turns",
  "debug.fallbackTurns": "Fallback turns",
  "debug.apiTasks": "API tasks",
  "debug.exportReport": "Export Report",
  "debug.exportReportDone": "Exported {filename}",
  "debug.exportTaskLog": "Export Task Log",
  "debug.exportTaskLogDone": "Exported {filename}",
  "toolbar.layout": "Layout",
  "toolbar.suggestLinks": "Suggest Links",
  "toolbar.suggesting": "Suggesting...",
  "toolbar.analyzeTopics": "Analyze Topics",
  "toolbar.analyzingTopics": "Analyzing...",
  "toolbar.search": "Search",
  "toolbar.undo": "Undo",
  "toolbar.redo": "Redo",
  "toolbar.summarizeAll": "Summarize All",
  "toolbar.summarizing": "Summarizing...",
  "toolbar.files": "Files",
  "file.importJson": "Import JSON",
  "file.exportJson": "Export JSON",
  "file.exportCanvas": "Export Canvas",
  "file.exportOpml": "Export OPML",
  "file.exportObsidianVault": "Export Obsidian Vault",
  "file.exportSvg": "Export SVG",
  "file.exportPng": "Export PNG",
  "file.exportMd": "Export MD",
  "file.copyMd": "Copy MD",
  "file.resetMap": "Reset Map",
  "file.exported": "Exported {filename}",
  "file.importedJson": "Imported ChatMap JSON: {nodes} nodes, {links} user links.",
  "file.importJsonFailed": "ChatMap JSON import failed.",
  "file.markdownCopied": "Markdown copied to clipboard.",
  "file.markdownCopyFailed": "Clipboard copy failed. Try Markdown export instead.",
  "file.exportPngFailed": "PNG export failed.",
  "file.resetConfirm": "Reset this ChatMap? This clears saved positions, edits, notes, hidden nodes, and links for the current conversation.",
  "file.resetDone": "Current map reset.",
  "file.undoDone": "Undo.",
  "file.redoDone": "Redo.",
  "search.title": "Search Map",
  "search.close": "Close",
  "search.placeholder": "Search title, summary, tag...",
  "search.empty": "No matching nodes.",
  "suggestions.title": "Link Suggestions",
  "suggestions.acceptAll": "Accept All",
  "suggestions.accept": "Accept",
  "suggestions.reject": "Reject",
  "suggestions.clear": "Clear",
  "suggestions.acceptedStatus": "Accepted link: {source} -> {target}.",
  "suggestions.acceptedAllStatus": "Accepted {count} link suggestions.",
  "suggestions.rejectedStatus": "Rejected link suggestion.",
  "suggestions.clearedStatus": "Cleared {count} link suggestions.",
  "settings.title": "ChatMap Settings",
  "settings.documentTitle": "ChatMap Settings",
  "settings.subtitle": "Manage global settings without crowding the map workspace.",
  "settings.close": "Close",
  "settings.status.local": "Settings are stored locally in this browser profile.",
  "settings.status.interfaceSaved": "Interface settings saved.",
  "settings.section.interface": "Interface",
  "settings.section.interfaceHint": "Defaults for map views and supported-site page helpers",
  "settings.group.appearance": "Appearance and language",
  "settings.group.appearanceHint": "Theme and UI language for ChatMap surfaces.",
  "settings.group.languagePacks": "Language packs",
  "settings.group.languagePacksHint": "Generate, import, or export custom UI translations.",
  "settings.group.mapDefaults": "Map defaults",
  "settings.group.mapDefaultsHint": "Node sizing, link shape, and color rendering.",
  "settings.graphLayout.title": "Conversation graph layout",
  "settings.graphLayout.hint": "Choose how conversation turns are arranged in the graph.",
  "settings.graphLayout.mode": "Layout mode",
  "settings.graphLayout.modeHint": "Snake lays turns out in order and replaces old topic-based automatic links.",
  "settings.graphLayout.columns": "Turns per row",
  "settings.graphLayout.columnsHint": "Choose from 3 to 15 turns in each row.",
  "settings.graphLayout.horizontalSpacing": "Horizontal spacing",
  "settings.graphLayout.verticalSpacing": "Vertical spacing",
  "settings.graphLayout.spacingHint": "Distance between grid positions.",
  "settings.graphLayout.arrangement": "Row direction",
  "settings.graphLayout.snake": "Snake (recommended)",
  "settings.graphLayout.leftToRight": "Every row left to right",
  "settings.graphLayout.showSequenceEdges": "Show automatic sequence edges",
  "settings.graphLayout.applyHint": "Saving these settings reapplies the grid to the open map without changing turn content or order.",
  "settings.group.pageHelpers": "Supported-site helpers",
  "settings.group.pageHelpersHint": "Controls shown directly on AI conversation pages.",
  "settings.customSites.title": "Custom sites",
  "settings.customSites.hint": "Selector-only profiles are stored locally. An exact-origin permission and a successful preview are required before use.",
  "settings.customSites.name": "Display name",
  "settings.customSites.origin": "Exact origin",
  "settings.customSites.pathPattern": "Path pattern",
  "settings.customSites.conversationRoot": "Conversation root selector",
  "settings.customSites.userSelector": "User message selector",
  "settings.customSites.assistantSelector": "Assistant message selector",
  "settings.customSites.titleSelector": "Title selector (optional)",
  "settings.customSites.scrollContainer": "Scroll container selector (optional)",
  "settings.customSites.messageIdAttributes": "Stable ID attributes",
  "settings.customSites.selectorHint": "CSS selectors only. Scripts, broad wildcard origins, and built-in site overrides are rejected.",
  "settings.customSites.save": "Save disabled profile",
  "settings.customSites.cancel": "Cancel editing",
  "settings.customSites.savedDisabled": "Profile saved locally and disabled until validation succeeds.",
  "settings.customSites.invalid": "Profile validation failed.",
  "settings.customSites.validating": "Requesting exact-origin access and previewing the active page...",
  "settings.customSites.validateEnable": "Validate & enable",
  "settings.customSites.permissionDenied": "Exact-origin permission was not granted; the profile remains disabled.",
  "settings.customSites.previewFailed": "Preview failed; the profile remains disabled.",
  "settings.customSites.reason.permission-required": "Permission required",
  "settings.customSites.reason.preview-required": "Preview required",
  "settings.customSites.reason.permission-denied": "Permission denied",
  "settings.customSites.reason.preview-failed": "Preview failed",
  "settings.customSites.enabled": "Enabled",
  "settings.customSites.disabled": "Disabled",
  "settings.customSites.edit": "Edit",
  "settings.customSites.disable": "Disable",
  "settings.customSites.delete": "Delete",
  "settings.customSites.deleteConfirm": "Delete this custom site profile?",
  "settings.customSites.empty": "No custom site profiles yet.",
  "settings.customSites.previewSummary": "Active-page preview",
  "settings.customSites.importMode": "Import mode",
  "settings.customSites.merge": "Merge with local profiles",
  "settings.customSites.replace": "Replace local profiles",
  "settings.customSites.import": "Import custom sites",
  "settings.customSites.export": "Export custom sites",
  "settings.customSites.importDone": "Imported {count} profiles. Imported profiles remain disabled until validated.",
  "settings.customSites.importFailed": "Custom sites import failed.",
  "settings.customSites.exportDone": "Custom sites backup exported.",
  "promptWorkbench.title": "Prompt Workbench",
  "promptWorkbench.subtitle": "Manage local prompts, variables, and current-input AI optimization.",
  "promptWorkbench.loading": "Loading prompt workbench...",
  "promptWorkbench.enabled": "Enable ChatGPT input-side prompt workbench",
  "promptWorkbench.preview": "Preview AI optimization before writing it back",
  "promptWorkbench.group.behavior": "Behavior",
  "promptWorkbench.group.behaviorHint": "Controls the lightweight icon entry, write-back mode, and optimization format.",
  "promptWorkbench.group.library": "Prompt library",
  "promptWorkbench.group.libraryHint": "One-level folders, tags, pinning, and editable local prompt templates.",
  "promptWorkbench.group.optimizer": "AI optimization prompts",
  "promptWorkbench.group.optimizerHint": "Built-in optimizer prompts are fully editable and exported with backups.",
  "promptWorkbench.group.backup": "Backup and import",
  "promptWorkbench.group.backupHint": "Exports are local JSON files. API keys and current inputs are never included.",
  "promptWorkbench.format": "AI optimization format",
  "promptWorkbench.format.simple-polish": "Simple polish",
  "promptWorkbench.format.strict-planning": "Strict planning table",
  "promptWorkbench.applyMode": "Default apply mode",
  "promptWorkbench.apply.smart": "Smart",
  "promptWorkbench.apply.insert": "Insert",
  "promptWorkbench.apply.append": "Append",
  "promptWorkbench.apply.replace": "Replace",
  "promptWorkbench.apply.wrapSelection": "Wrap selection",
  "promptWorkbench.panelSide": "Panel side",
  "promptWorkbench.panelSide.auto": "Auto",
  "promptWorkbench.panelSide.left": "Left",
  "promptWorkbench.panelSide.right": "Right",
  "promptWorkbench.search": "Search title, content, tag...",
  "promptWorkbench.allPrompts": "All prompts",
  "promptWorkbench.noTags": "No tags",
  "promptWorkbench.noFolder": "No folder",
  "promptWorkbench.moveUp": "Move up",
  "promptWorkbench.moveDown": "Move down",
  "promptWorkbench.folder.add": "New folder",
  "promptWorkbench.folder.delete": "Delete folder",
  "promptWorkbench.prompt.new": "New prompt",
  "promptWorkbench.prompt.delete": "Delete prompt",
  "promptWorkbench.prompt.title": "Title",
  "promptWorkbench.prompt.folder": "Folder",
  "promptWorkbench.prompt.content": "Prompt content",
  "promptWorkbench.prompt.tags": "Tags",
  "promptWorkbench.prompt.note": "Note",
  "promptWorkbench.prompt.enabled": "Enabled",
  "promptWorkbench.prompt.pinned": "Pinned",
  "promptWorkbench.prompt.empty": "Select or create a prompt.",
  "promptWorkbench.optimizer.simple": "Simple polish prompt",
  "promptWorkbench.optimizer.strict": "Strict planning prompt",
  "promptWorkbench.optimizer.restoreDefault": "Restore default optimizer prompts",
  "promptWorkbench.importMode": "Import mode",
  "promptWorkbench.import.mergeOverwrite": "Merge: overwrite same title",
  "promptWorkbench.import.mergeSkip": "Merge: skip same title",
  "promptWorkbench.import.replace": "Replace entire library",
  "promptWorkbench.import.settings": "Import workbench settings",
  "promptWorkbench.import.optimizer": "Import optimizer prompts",
  "promptWorkbench.import.file": "Prompt workbench backup",
  "promptWorkbench.import.choose": "Choose file",
  "promptWorkbench.import.noFile": "No file selected",
  "promptWorkbench.export": "Export backup",
  "promptWorkbench.save": "Save Prompt Workbench",
  "promptWorkbench.status.saved": "Prompt workbench saved.",
  "promptWorkbench.status.exported": "Prompt workbench backup exported.",
  "promptWorkbench.status.imported": "Imported prompt backup: {added} added, {updated} updated, {skipped} skipped.",
  "promptWorkbench.status.importFailed": "Prompt workbench import failed.",
  "promptWorkbench.confirm.deletePrompt": "Delete this prompt?",
  "promptWorkbench.confirm.deleteFolder": "Delete this folder? Prompts in it will move to No folder.",
  "promptWorkbench.confirm.replace": "Replace the entire local prompt library? This cannot be undone.",
  "promptWorkbench.action.optimize": "Optimize prompt",
  "promptWorkbench.aria.launcher": "Open Prompt Workbench",
  "promptWorkbench.content.library": "Prompt library",
  "floatingNavigator.view.all": "All turns",
  "floatingNavigator.view.favorites": "Favorites",
  "floatingNavigator.action.addFavorite": "Favorite this turn",
  "floatingNavigator.action.removeFavorite": "Remove from favorites",
  "floatingNavigator.action.jump": "Jump to this conversation turn",
  "floatingNavigator.empty.all": "No mapped turns yet.",
  "floatingNavigator.empty.favorites": "No favorite turns yet.",
  "floatingNavigator.unavailable": "Original turn is temporarily unavailable.",
  "floatingNavigator.turn": "Turn {number}",
  "promptWorkbench.content.optimize": "Optimize prompt",
  "promptWorkbench.content.imagePrompt": "Image prompt",
  "promptWorkbench.content.variables": "Variables",
  "promptWorkbench.content.manage": "Manage prompts",
  "promptWorkbench.content.selectedText": "Selected text",
  "promptWorkbench.content.searchPrompts": "Search prompts...",
  "promptWorkbench.content.searchHint": "Pinned, recent, and folder prompts are searched together.",
  "promptWorkbench.content.apply": "Apply",
  "promptWorkbench.content.insert": "Insert",
  "promptWorkbench.content.append": "Append",
  "promptWorkbench.content.replace": "Replace",
  "promptWorkbench.content.chooseApply": "Choose how to apply this prompt to the current input.",
  "promptWorkbench.content.selectVariables": "Select a prompt with variables first.",
  "promptWorkbench.content.missing": "Missing: {names}",
  "promptWorkbench.content.inputMissing": "Could not find the ChatGPT input box.",
  "promptWorkbench.content.writeSomething": "Write something first, then optimize it.",
  "promptWorkbench.content.optimizing": "Optimizing current input...",
  "promptWorkbench.content.optimizedPrompt": "Optimized prompt",
  "promptWorkbench.content.strictPlanningSuggestions": "Strict planning suggestions",
  "promptWorkbench.content.optimizationFailed": "AI optimization failed.",
  "promptWorkbench.content.errorDetails": "Error details",
  "promptWorkbench.content.optimizeStage.readInput": "Failed while reading the current ChatGPT input. This is usually an input box or text selection issue, not an API key problem.",
  "promptWorkbench.content.optimizeStage.requestChatCompletion": "Failed while requesting your configured AI provider. Check the provider, model, quota, host permission, or network details below.",
  "promptWorkbench.content.optimizeStage.writeInput": "Failed while writing the optimized prompt back to the ChatGPT input box. The page may have remounted the editor.",
  "promptWorkbench.content.optimizeFailureHint": "The raw error below is sanitized and should help identify whether this is input reading, provider request, or write-back.",
  "promptWorkbench.content.openAiSettings": "Open AI settings",
  "promptWorkbench.content.copy": "Copy",
  "promptWorkbench.content.imagePromptConcept": "Start from the current input, then choose image prompt constraints below.",
  "promptWorkbench.content.imagePromptCustom": "Custom option...",
  "promptWorkbench.content.imagePromptAddCustom": "Add custom option",
  "promptWorkbench.content.imagePromptRandom": "Random",
  "promptWorkbench.content.imagePromptGenerate": "Optimize",
  "promptWorkbench.content.imagePromptSavePreset": "Save preset",
  "promptWorkbench.content.imagePromptPresetSaved": "Image prompt preset saved.",
  "settings.defaultLayout": "Default layout",
  "layout.single": "Single-side",
  "layout.snake": "Snake / Sequential",
  "layout.radial": "Radial",
  "layout.matrix": "Matrix",
  "layout.twoSided": "Two-sided",
  "relationship.related": "Related",
  "relationship.dependsOn": "Depends on",
  "relationship.extends": "Extends",
  "relationship.supports": "Supports",
  "relationship.contradicts": "Contradicts",
  "relationship.contrasts": "Contrasts",
  "relationship.duplicates": "Duplicates",
  "relationship.verifies": "Verifies",
  "relationship.references": "References",
  "relationship.todo": "Todo",
  "node.conversation": "Conversation",
  "node.note": "Note",
  "node.turn": "Turn {number}",
  "node.ai": "AI",
  "node.aiWorking": "AI...",
  "panel.nodesSelected": "{count} Nodes Selected",
  "panel.organizeSelected": "Organize selected turns as notes or review groups.",
  "panel.nodeActions": "Node Actions",
  "panel.nodeHint": "Create notes, split this turn, or start bulk organization.",
  "panel.miniNodeActions": "Mini Node Actions",
  "panel.miniNodeHint": "Edit the selected mini node without changing the AI-generated structure.",
  "panel.linkTitle": "Link Actions",
  "panel.linksSelected": "{count} Links Selected",
  "panel.linkBatchHint": "Apply changes to all selected links.",
  "panel.headerTitle": "Header",
  "panel.headerHint": "Double-click the header text to edit it.",
  "field.title": "Title",
  "field.type": "Type",
  "field.label": "Label",
  "field.tag": "Tag",
  "field.tagPlaceholder": "Add tag...",
  "action.close": "Close",
  "action.mergeNodes": "Merge Nodes",
  "action.collapseTopic": "Collapse Topic",
  "action.expandTopicGroup": "Expand Topic",
  "action.addTag": "Add Tag",
  "action.removeTag": "Remove",
  "action.colorNode": "Color",
  "action.collapseNode": "Fold",
  "action.expandNode": "Unfold",
  "action.open": "Open",
  "action.review": "Review",
  "action.done": "Done",
  "action.duplicateAsNote": "Duplicate as Note",
  "action.splitNode": "Split Node",
  "action.selectAllTurns": "Select All Turns",
  "action.important": "Important",
  "action.edgeWeight": "Weight",
  "action.convertToNote": "Convert to Note",
  "action.deleteLink": "Delete Link",
  "action.deleteMiniNode": "Delete",
  "action.expandAnswer": "Generate Mini Map",
  "action.reexpandAnswer": "Re-expand",
  "action.showOriginal": "Show Original",
  "action.showExpansion": "Show Expanded",
  "action.deleteExpansion": "Delete Expansion",
  "action.restoreNodeSize": "Restore Size",
  "action.rebuildNode": "Rebuild Node",
  "action.deleteHeader": "Delete Header",
  "app.confirm.deleteMiniSubtree": "Delete this mini node and {count} related mini nodes?",
  "label.confidence": "Confidence",
  "color.theme": "Theme",
  "color.slate": "Slate",
  "color.blue": "Blue",
  "color.emerald": "Emerald",
  "color.amber": "Yellow",
  "color.red": "Red",
  "color.violet": "Violet",
  "color.cyan": "Cyan",
  "color.rose": "Brown",
  "status.nodesCollapsed": "Selected nodes folded.",
  "status.nodesExpanded": "Selected nodes unfolded.",
  "status.nodesImportant": "Selected nodes marked important.",
  "status.nodesNormal": "Selected nodes unmarked important.",
  "status.nodeResized": "Node size saved.",
  "status.nodeSizeRestored": "Node size restored.",
  "status.nodeRebuilt": "Node rebuilt with default content and appearance.",
  "status.expansionDeleted": "Answer expansion deleted.",
  "status.tagAdded": "Added tag to {count} nodes.",
  "status.tagRemoved": "Removed {tag} from {count} nodes.",
  "status.linksUpdated": "Updated {count} links.",
  "status.topicCollapsed": "Collapsed {count} nodes into a topic.",
  "status.topicExpanded": "Expanded topic and restored {count} nodes.",
  "status.topicNestedRejected": "Topic groups cannot be nested.",
  "expansion.emptyGuidance": "This expansion has fewer than two mini nodes. Restore the original answer or run AI expansion again.",
  "task.summarizeOne": "Summarizing turn {current}... 5%",
  "task.summarizeOneDone": "Turn {current} summarized. 100%",
  "task.summarizeNote": "Summarizing #AI note from {count} source turns... 5%",
  "task.summarizeNoteDone": "#AI note summarized. 100%",
  "task.summarizeAll": "Summarizing {total} turns... 0%",
  "task.summarizeProgress": "AI task progress: {current}/{total}",
  "task.summarizeAllDone": "Batch summary finished: {total} turns updated. 100%",
  "task.summarizeFailed": "AI summary failed.",
  "task.summarizeSkippedEdited": "Skipped AI summary because title and summary were already edited.",
  "task.summarizeNoteNeedsSource": "#AI note needs at least one source turn before it can be summarized.",
  "task.autoSummarize": "Auto summarizing {total} default nodes... 0%",
  "task.autoSummarizeDone": "Auto summarize finished: {total} nodes updated. 100%",
  "task.autoSummarizeFailed": "Auto summarize failed.",
  "task.suggestLinks": "Asking AI to suggest semantic links... 15%",
  "task.suggestLinksRequesting": "Waiting for AI link suggestions... 45%",
  "task.suggestLinksFiltering": "Filtering link suggestions... 85%",
  "task.suggestLinksDone": "{count} AI link suggestions ready for review. 100%",
  "task.suggestLinksFailed": "AI link suggestion failed.",
  "task.analyzeTopics": "Analyzing local topic signals... 20%",
  "task.analyzeTopicsDone": "{count} topic link candidates ready for review. 100%",
  "task.analyzeTopicsNone": "No strong topic link candidates found. 100%",
  "task.analyzeTopicsFailed": "Topic analysis failed.",
  "task.expandAnswer": "Preparing answer expansion... 10%",
  "task.expandAnswerPreparing": "Preparing answer text for expansion... 12%",
  "task.expandAnswerOutline": "Reading headings, lists, and bold structure cues... 28%",
  "task.expandAnswerRequesting": "Asking AI to build the mini-map... 55%",
  "task.expandAnswerValidating": "Validating mini-map structure... 78%",
  "task.expandAnswerLayout": "Fitting the mini-map layout... 90%",
  "task.expandAnswerDone": "Answer expansion ready. 100%",
  "task.expandAnswerFailed": "Answer expansion failed.",
  "task.graphHealthDone": "Graph health repaired: {corrected} corrected, {dropped} dropped, {fatal} fatal. 100%",
  "task.translate": "Translating ChatMap UI to {language}... 10%",
  "task.translateDone": "Translation generated for {language}. 100%",
  "settings.theme": "Theme",
  "settings.theme.browser": "Follow browser",
  "settings.theme.day": "Day",
  "settings.theme.night": "Night",
  "settings.theme.eyeCare": "Eye-care",
  "settings.language": "Language",
  "settings.language.browser": "Follow browser",
  "settings.language.english": "English",
  "settings.language.chinese": "Chinese",
  "settings.languageHint": "Built-in Chinese and English follow the browser by default.",
  "settings.linkConnectionStyle": "Link style",
  "settings.linkConnectionStyleCurved": "Curved",
  "settings.linkConnectionStyleAngled": "Angled",
  "settings.defaultNodeSize": "Default node size",
  "settings.defaultNodeWidth": "Node width",
  "settings.defaultNodeWidthHint": "Default 280 px. Used for newly generated nodes and size restore.",
  "settings.defaultNodeHeight": "Node height",
  "settings.defaultNodeHeightHint": "Default 220 px. Used for newly generated nodes and size restore.",
  "settings.defaultNodePromptRatio": "User input share",
  "settings.defaultNodePromptRatioHint": "Controls the displayed line share between user input and AI answer: 0, 25, 50, 75, or 100%.",
  "settings.customLanguage": "Custom language",
  "settings.customLanguagePlaceholder": "Spanish, Japanese, German...",
  "settings.languageCode": "Language code",
  "settings.languageCodePlaceholder": "fr-FR, ja-JP, de-DE...",
  "settings.generateTranslation": "Generate with AI",
  "settings.generatingTranslation": "Generating...",
  "settings.importLanguagePack": "Import language pack",
  "settings.exportLanguagePack": "Export language pack",
  "settings.languagePackChooseFile": "Choose file",
  "settings.languagePackNoFile": "No file selected",
  "settings.languagePackSelected": "Selected: {filename}",
  "settings.customTranslationHint":
    "AI translation only sends ChatMap UI labels, not your conversation content. Generated labels are stored locally.",
  "settings.translationRepairHint":
    "If the model returns invalid JSON, ChatMap may make one extra API call to repair the language pack format.",
  "settings.enableFloat": "Enable Float navigator by default",
  "settings.showLauncher": "Show ChatMap launcher on supported AI pages",
  "settings.nodeColorRendering": "Node color rendering",
  "settings.nodeColorRenderMode": "Render mode",
  "settings.nodeColorRenderGradient": "Gradient",
  "settings.nodeColorRenderSolid": "Solid",
  "settings.nodeColorRenderStrength": "Render strength",
  "settings.saveInterface": "Save Interface",
  "settings.loadingInterface": "Loading interface settings...",
  "settings.section.updates": "Updates",
  "settings.section.updatesHint": "Preview controls for release notifications",
  "settings.showUpdates": "Show update notices when available",
  "settings.includePrerelease": "Include pre-release versions",
  "settings.ignoredVersion": "Ignored version",
  "settings.ignoredVersionPlaceholder": "v0.1.1",
  "settings.updateHint":
    "GitHub/unpacked installs cannot be silently updated by the extension. Update notices will point users to a release page or package when this feature is connected.",
  "settings.saveUpdates": "Save Updates",
  "settings.loadingUpdates": "Loading update settings...",
  "settings.translationSaved": "Generated translation saved.",
  "settings.translationNeedsName": "Enter a target language name first.",
  "settings.translationNeedsCode": "Enter a language code first.",
  "settings.translationFailed": "AI translation failed.",
  "settings.languageImportDone": "Imported {language}. Missing labels fall back to English: {count}.",
  "settings.languageImportFailed": "Language pack import failed.",
  "settings.languageImportConflict": "A custom language with the same code already exists. Replace it?",
  "settings.languageImportCancelled": "Language pack import cancelled.",
  "settings.languageExportNeedsCustom": "Select a custom language before exporting.",
  "settings.languageExportDone": "Exported {language} language pack.",
  "ai.title": "AI Provider",
  "ai.subtitle": "OpenAI-compatible chat completions",
  "ai.provider": "Provider",
  "ai.customCompatible": "Custom compatible",
  "ai.baseUrl": "Base URL",
  "ai.baseUrlPlaceholder": "https://api.example.com/v1",
  "ai.model": "Model",
  "ai.modelPlaceholder": "model-name",
  "ai.apiKey": "API Key",
  "ai.apiKeyPlaceholder": "Stored locally",
  "ai.apiKeyRawHint":
    "Paste the raw API key only. Do not include the Bearer prefix; ChatMap adds the Authorization header for you.",
  "ai.maxTokens": "Max output tokens",
  "ai.maxTokensPlaceholder": "4000",
  "ai.maxTokensHint":
    "This is the output limit, not the model context window. ChatMap uses a conservative higher budget for long-answer summaries; increase this only when your provider and model support it.",
  "ai.providerPresetLimit":
    "Provider presets are convenience defaults. Accounts, regions, model names, JSON mode, and context windows can vary by provider.",
  "ai.providerNote.openai": "Default: gpt-5.4-nano for fast, lower-cost long-context OpenAI-compatible work.",
  "ai.providerNote.deepseek": "Default: deepseek-v4-flash. Older deepseek-chat settings remain usable but are not the fresh default.",
  "ai.providerNote.openrouter": "Default: qwen/qwen3.5-flash-02-23 through OpenRouter's normalized API.",
  "ai.providerNote.qwen": "Default: qwen3.5-flash through DashScope compatible mode.",
  "ai.providerNote.kimi": "Default: kimi-k2.6. JSON mode is not forced for this preset.",
  "ai.providerNote.doubao":
    "Default: Doubao Ark compatible endpoint. Some Volcano Ark accounts use an endpoint ID in the Model field.",
  "ai.providerNote.zhipu": "Default: glm-4.7-flash through BigModel chat completions.",
  "ai.providerNote.mistral": "Default: mistral-small-2603 with structured chat completion support.",
  "ai.providerNote.geminiCompatible":
    "Gemini compatible requires a Vertex project/location endpoint and an OAuth Bearer token, not a normal static API key.",
  "ai.providerNote.custom": "Custom remains the fallback for any OpenAI-compatible chat completions endpoint.",
  "ai.privacy":
    "API keys are saved in this browser's extension storage. ChatMap sends conversation text only when you run AI features or enable auto summarize.",
  "ai.autoSummarize": "Auto summarize new/default nodes",
  "ai.status.local": "Settings are stored locally. AI features send selected conversation text to your configured provider.",
  "ai.status.saved": "Saved.",
  "ai.status.aiSaved": "AI settings saved.",
  "ai.status.testing": "Testing connection...",
  "ai.status.connectionSaved": "Connection succeeded. Settings saved.",
  "ai.status.connectionSavedGlobal": "AI connection succeeded. Settings saved.",
  "ai.status.failed": "Connection test failed.",
  "ai.save": "Save",
  "ai.test": "Test Connection",
  "ai.testing": "Testing..."
} as const;

export type I18nKey = keyof typeof EN_TRANSLATIONS;
export type TranslationMap = Record<I18nKey, string>;

export const ZH_TRANSLATIONS: TranslationMap = {
  ...EN_TRANSLATIONS,
  "action.expandTopicGroup": "展开主题",
  "action.removeTag": "移除",
  "status.nodeResized": "节点尺寸已保存。",
  "status.nodeSizeRestored": "节点大小已还原。",
  "status.nodeRebuilt": "节点已按默认内容与外观重建。",
  "status.expansionDeleted": "回答展开已删除。",
  "status.tagAdded": "已向 {count} 个节点添加标签。",
  "status.tagRemoved": "已从 {count} 个节点移除 {tag}。",
  "status.linksUpdated": "已更新 {count} 条链接。",
  "status.topicCollapsed": "已将 {count} 个节点折叠为主题。",
  "status.topicExpanded": "已展开主题并恢复 {count} 个节点。",
  "status.topicNestedRejected": "主题折叠不能嵌套。",
  "expansion.emptyGuidance": "这个展开结果少于两个 mini 节点。请恢复原回答或重新运行 AI 展开。",
  "task.expandAnswer": "正在准备回答展开... 10%",
  "task.expandAnswerPreparing": "正在准备回答文本... 12%",
  "task.expandAnswerOutline": "正在读取标题、列表和加粗结构线索... 28%",
  "task.expandAnswerRequesting": "正在请求 AI 生成 mini 思维导图... 55%",
  "task.expandAnswerValidating": "正在校验 mini 思维导图结构... 78%",
  "task.expandAnswerLayout": "正在适配 mini 思维导图布局... 90%",
  "task.expandAnswerDone": "回答展开已完成。100%",
  "task.expandAnswerFailed": "回答展开失败。",
  "task.graphHealthDone": "图谱卫生修复：已修正 {corrected} 项，已丢弃 {dropped} 项，严重 {fatal} 项。100%",
  "panel.linksSelected": "已选择 {count} 条链接",
  "panel.linkBatchHint": "将修改应用到所有选中的链接。",
  "field.tag": "标签",
  "field.tagPlaceholder": "添加标签...",
  "action.deleteMiniNode": "删除",
  "panel.miniNodeActions": "Mini 节点操作",
  "panel.miniNodeHint": "编辑选中的 mini 节点，不改变 AI 生成的整体结构。",
  "field.title": "标题",
  "action.expandAnswer": "生成迷你导图",
  "action.reexpandAnswer": "重新展开",
  "action.showOriginal": "显示原文",
  "action.showExpansion": "显示展开",
  "action.deleteExpansion": "删除展开",
  "action.restoreNodeSize": "还原大小",
  "action.rebuildNode": "重建节点",
  "app.confirm.deleteExpansion": "删除这个回答展开？原回答会保留，但 mini 思维导图编辑会被移除。",
  "app.confirm.deleteMiniSubtree": "删除这个 mini 节点及相关的 {count} 个 mini 节点吗？",
  "app.confirm.reexpandAnswer": "用 AI 重新展开这个回答？这可能覆盖已有 mini 思维导图编辑。",
  "app.documentTitle": "ChatMap",
  "app.documentTitle.fullPage": "ChatMap 全屏页",
  "app.kicker": "对话思维导图",
  "app.subtitle.hasTurns": "右键点击轮次节点即可跳回原网页对应消息。",
  "app.subtitle.noTurns": "还没有找到完整问答轮次。",
  "jump.heading.pending": "正在跳回原消息",
  "jump.heading.success": "已完成跳转",
  "jump.heading.error": "无法跳回原消息",
  "jump.inProgress": "正在网页中定位第 {number} 轮对话…",
  "jump.succeeded": "已在网页中定位到第 {number} 轮对话。",
  "jump.failed": "跳转失败，但网页没有返回具体原因。",
  "jump.missingTurn": "此节点没有关联到已抓取的对话轮次。",
  "jump.dismiss": "关闭提示",
  "app.empty.title": "还没有地图",
  "app.empty.hint": "请打开一个至少包含一条完整回答的受支持 AI 对话。",
  "app.action.refresh": "刷新",
  "app.action.refreshing": "扫描中…",
  "app.action.rebuild": "重建",
  "app.action.refreshIndex": "刷新索引",
  "app.action.scanning": "正在扫描索引…",
  "app.action.settings": "设置",
  "app.action.debug": "调试",
  "app.action.view": "视图",
  "app.view.sidePanel": "侧边栏",
  "app.view.fullPage": "全屏页",
  "app.view.showFloat": "显示浮窗",
  "app.view.hideFloat": "隐藏浮窗",
  "app.view.current": "当前",
  "app.status.waiting": "正在等待 AI 对话...",
  "app.status.cacheFailed": "对话已加载，但 IndexedDB 缓存失败。",
  "app.status.mappedVia": "已通过 {source} 映射 {count} 个节点",
  "app.status.loadedTurns": "已映射 {count} 个已加载节点",
  "app.status.refreshAdded": "刷新已新增 {added} 个节点，共 {total} 个。",
  "app.status.refreshNoNew": "刷新未发现新节点，共 {total} 个。",
  "app.status.refreshIndexAdded": "索引刷新补充 {added} 个当前可用节点，共 {total} 个。",
  "app.status.refreshIndexNoNew": "索引刷新未发现新的当前可用节点，共 {total} 个。",
  "app.status.refreshIndexReordered": "已重新扫描并按对话顺序排列 {total} 个节点。",
  "app.status.refreshIndexOrderKept": "本次只扫描到 {scanned} 轮，未覆盖已保存的 {total} 轮；为防止丢记录，保留了原图谱顺序。",
  "app.status.refreshRecomputed": "已重新扫描 ChatGPT 对话，并重算 {total} 个轮次节点和布局。",
  "app.status.refreshScanFailed": "对话扫描失败：{reason}。已保留现有图谱。",
  "app.status.restoredConversation": "已恢复这个对话保存过的思维导图，共 {count} 个节点。",
  "app.status.switchReadingIndex": "切换思维导图前正在刷新这个对话的索引...",
  "app.status.switchCreated": "已为这个对话建立思维导图，共 {count} 个节点。",
  "app.status.switchReadFailed": "未能读取这个对话，已保留当前思维导图。",
  "app.status.reading": "正在读取新加载的 AI 对话轮次...",
  "app.status.rebuilding": "正在根据已保存的轮次重新计算布局...",
  "app.status.rebuilt": "已根据 {count} 轮对话重建思维导图。",
  "app.status.rebuildNoTurns": "还没有已保存的轮次可供重建。",
  "app.status.refreshScanEmpty": "页面扫描没有返回轮次，已保留现有图谱。",
  "app.status.openConversation": "请打开一个受支持的 AI 对话标签页，然后刷新 ChatMap。",
  "app.status.refreshingIndex": "正在刷新当前可用的对话索引...",
  "app.status.refreshIndexFailed": "索引刷新无法连接到当前对话标签页。",
  "app.status.noActiveTab": "没有找到当前活动的受支持 AI 对话标签页。",
  "app.status.floatEnabled": "浮窗已启用",
  "app.status.floatDisabled": "浮窗已关闭",
  "app.status.floatFailed": "无法连接到对话标签页以显示浮窗。",
  "app.status.layoutSet": "布局已切换为 {layout}",
  "debug.conversation": "对话",
  "debug.site": "站点",
  "debug.id": "ID",
  "debug.turns": "轮次",
  "debug.source": "来源",
  "debug.selectorTurns": "选择器轮次",
  "debug.fallbackTurns": "备用选择器轮次",
  "debug.apiTasks": "API 任务",
  "debug.exportReport": "导出报告",
  "debug.exportReportDone": "已导出 {filename}",
  "debug.exportTaskLog": "导出任务日志",
  "debug.exportTaskLogDone": "已导出 {filename}",
  "toolbar.layout": "布局",
  "toolbar.suggestLinks": "建议链接",
  "toolbar.suggesting": "建议中...",
  "toolbar.analyzeTopics": "分析主题",
  "toolbar.analyzingTopics": "分析中...",
  "toolbar.search": "搜索",
  "toolbar.undo": "撤销",
  "toolbar.redo": "重做",
  "toolbar.summarizeAll": "全部总结",
  "toolbar.summarizing": "总结中...",
  "toolbar.files": "文件",
  "file.importJson": "导入 JSON",
  "file.exportJson": "导出 JSON",
  "file.exportCanvas": "导出 Canvas",
  "file.exportOpml": "导出 OPML",
  "file.exportObsidianVault": "导出 Obsidian Vault",
  "file.exportSvg": "导出 SVG",
  "file.exportPng": "导出 PNG",
  "file.exportMd": "导出 MD",
  "file.copyMd": "复制 MD",
  "file.resetMap": "重置导图",
  "file.exported": "已导出 {filename}",
  "file.importedJson": "已导入 ChatMap JSON：{nodes} 个节点，{links} 条用户链接。",
  "file.importJsonFailed": "ChatMap JSON 导入失败。",
  "file.markdownCopied": "Markdown 已复制到剪贴板。",
  "file.markdownCopyFailed": "剪贴板复制失败，请改用 Markdown 导出。",
  "file.exportPngFailed": "PNG 导出失败。",
  "file.resetConfirm": "重置当前 ChatMap？这会清除当前对话已保存的位置、编辑、备注、隐藏节点和链接。",
  "file.resetDone": "当前导图已重置。",
  "file.undoDone": "已撤销。",
  "file.redoDone": "已重做。",
  "search.title": "搜索导图",
  "search.close": "关闭",
  "search.placeholder": "搜索标题、摘要、标签...",
  "search.empty": "没有匹配的节点。",
  "suggestions.title": "链接建议",
  "suggestions.acceptAll": "全部接受",
  "suggestions.accept": "接受",
  "suggestions.reject": "拒绝",
  "suggestions.clear": "清空",
  "suggestions.acceptedStatus": "已接受链接：{source} -> {target}。",
  "suggestions.acceptedAllStatus": "已接受 {count} 条链接建议。",
  "suggestions.rejectedStatus": "已拒绝链接建议。",
  "suggestions.clearedStatus": "已清空 {count} 条链接建议。",
  "settings.title": "ChatMap 设置",
  "settings.documentTitle": "ChatMap 设置",
  "settings.subtitle": "管理全局设置，让地图工作区保持清爽。",
  "settings.close": "关闭",
  "settings.status.local": "设置会保存在当前浏览器配置文件中。",
  "settings.status.interfaceSaved": "界面设置已保存。",
  "settings.section.interface": "界面",
  "settings.section.interfaceHint": "地图视图与受支持站点页面助手的默认设置",
  "settings.group.appearance": "外观与语言",
  "settings.group.appearanceHint": "控制 ChatMap 界面的主题和显示语言。",
  "settings.group.languagePacks": "语言包",
  "settings.group.languagePacksHint": "生成、导入或导出自定义界面翻译。",
  "settings.group.mapDefaults": "导图默认值",
  "settings.group.mapDefaultsHint": "节点大小、连接样式和染色渲染。",
  "settings.graphLayout.title": "对话图谱布局",
  "settings.graphLayout.hint": "选择对话轮次在图谱中的排列方式。",
  "settings.graphLayout.mode": "布局模式",
  "settings.graphLayout.modeHint": "蛇形布局按顺序排列轮次，并替换旧的主题自动连线。",
  "settings.graphLayout.columns": "每行节点数",
  "settings.graphLayout.columnsHint": "每行可设置 3 到 15 个节点。",
  "settings.graphLayout.horizontalSpacing": "水平间距",
  "settings.graphLayout.verticalSpacing": "垂直间距",
  "settings.graphLayout.spacingHint": "相邻网格位置之间的距离。",
  "settings.graphLayout.arrangement": "排列方向",
  "settings.graphLayout.snake": "蛇形排列（推荐）",
  "settings.graphLayout.leftToRight": "每行都从左到右",
  "settings.graphLayout.showSequenceEdges": "显示自动顺序连线",
  "settings.graphLayout.applyHint": "保存后会重新排布当前图谱，不会改变节点内容或 turn 顺序。",
  "settings.group.pageHelpers": "网页入口",
  "settings.group.pageHelpersHint": "控制 AI 对话网页中直接显示的 ChatMap 入口。",
  "settings.customSites.title": "自定义站点",
  "settings.customSites.hint": "仅使用选择器的配置仅保存在本地；必须授予精确域名权限并通过预览后才能启用。",
  "settings.customSites.name": "显示名称",
  "settings.customSites.origin": "精确来源域名",
  "settings.customSites.pathPattern": "路径模式",
  "settings.customSites.conversationRoot": "对话根节点选择器",
  "settings.customSites.userSelector": "用户消息选择器",
  "settings.customSites.assistantSelector": "助手消息选择器",
  "settings.customSites.titleSelector": "标题选择器（可选）",
  "settings.customSites.scrollContainer": "滚动容器选择器（可选）",
  "settings.customSites.messageIdAttributes": "稳定 ID 属性",
  "settings.customSites.selectorHint": "仅接受 CSS 选择器；脚本、宽泛通配来源和内置站点覆盖会被拒绝。",
  "settings.customSites.save": "保存为停用配置",
  "settings.customSites.cancel": "取消编辑",
  "settings.customSites.savedDisabled": "配置已保存在本地，验证成功前保持停用。",
  "settings.customSites.invalid": "配置验证失败。",
  "settings.customSites.validating": "正在请求精确域名权限并预览当前页面……",
  "settings.customSites.validateEnable": "验证并启用",
  "settings.customSites.permissionDenied": "未授予精确域名权限；配置仍保持停用。",
  "settings.customSites.previewFailed": "预览失败；配置仍保持停用。",
  "settings.customSites.reason.permission-required": "需要授予权限",
  "settings.customSites.reason.preview-required": "需要重新预览",
  "settings.customSites.reason.permission-denied": "权限被拒绝",
  "settings.customSites.reason.preview-failed": "预览失败",
  "settings.customSites.enabled": "已启用",
  "settings.customSites.disabled": "已停用",
  "settings.customSites.edit": "编辑",
  "settings.customSites.disable": "停用",
  "settings.customSites.delete": "删除",
  "settings.customSites.deleteConfirm": "删除此自定义站点配置？",
  "settings.customSites.empty": "暂无自定义站点配置。",
  "settings.customSites.previewSummary": "当前页面预览",
  "settings.customSites.importMode": "导入模式",
  "settings.customSites.merge": "与本地配置合并",
  "settings.customSites.replace": "替换本地配置",
  "settings.customSites.import": "导入自定义站点",
  "settings.customSites.export": "导出自定义站点",
  "settings.customSites.importDone": "已导入 {count} 个配置；导入项在验证前保持停用。",
  "settings.customSites.importFailed": "自定义站点导入失败。",
  "settings.customSites.exportDone": "自定义站点备份已导出。",
  "promptWorkbench.title": "提示词工作台",
  "promptWorkbench.subtitle": "管理本地提示词、变量和当前输入优化。",
  "promptWorkbench.loading": "正在加载提示词工作台...",
  "promptWorkbench.enabled": "在 ChatGPT 输入框旁启用提示词工作台",
  "promptWorkbench.preview": "AI 优化写回前先预览",
  "promptWorkbench.group.behavior": "行为",
  "promptWorkbench.group.behaviorHint": "控制轻量图标入口、写回方式和优化格式。",
  "promptWorkbench.group.library": "提示词库",
  "promptWorkbench.group.libraryHint": "一级文件夹、标签、置顶和可编辑的本地提示词模板。",
  "promptWorkbench.group.optimizer": "AI 优化提示词",
  "promptWorkbench.group.optimizerHint": "内置优化提示词可完全编辑，并会随备份导出。",
  "promptWorkbench.group.backup": "备份与导入",
  "promptWorkbench.group.backupHint": "导出为本地 JSON，不包含 API Key 或当前输入内容。",
  "promptWorkbench.format": "AI 优化格式",
  "promptWorkbench.format.simple-polish": "简单润色",
  "promptWorkbench.format.strict-planning": "严格规划表格",
  "promptWorkbench.applyMode": "默认应用方式",
  "promptWorkbench.apply.smart": "智能",
  "promptWorkbench.apply.insert": "插入",
  "promptWorkbench.apply.append": "追加",
  "promptWorkbench.apply.replace": "替换",
  "promptWorkbench.apply.wrapSelection": "包裹选中内容",
  "promptWorkbench.panelSide": "面板位置",
  "promptWorkbench.panelSide.auto": "自动",
  "promptWorkbench.panelSide.left": "左侧",
  "promptWorkbench.panelSide.right": "右侧",
  "promptWorkbench.search": "搜索标题、内容、标签...",
  "promptWorkbench.allPrompts": "全部提示词",
  "promptWorkbench.noTags": "无标签",
  "promptWorkbench.noFolder": "无文件夹",
  "promptWorkbench.moveUp": "上移",
  "promptWorkbench.moveDown": "下移",
  "promptWorkbench.folder.add": "新建文件夹",
  "promptWorkbench.folder.delete": "删除文件夹",
  "promptWorkbench.prompt.new": "新建提示词",
  "promptWorkbench.prompt.delete": "删除提示词",
  "promptWorkbench.prompt.title": "标题",
  "promptWorkbench.prompt.folder": "文件夹",
  "promptWorkbench.prompt.content": "提示词内容",
  "promptWorkbench.prompt.tags": "标签",
  "promptWorkbench.prompt.note": "备注",
  "promptWorkbench.prompt.enabled": "启用",
  "promptWorkbench.prompt.pinned": "置顶",
  "promptWorkbench.prompt.empty": "选择或新建一个提示词。",
  "promptWorkbench.optimizer.simple": "简单润色提示词",
  "promptWorkbench.optimizer.strict": "严格规划提示词",
  "promptWorkbench.optimizer.restoreDefault": "恢复默认优化提示词",
  "promptWorkbench.importMode": "导入模式",
  "promptWorkbench.import.mergeOverwrite": "合并：同名覆盖",
  "promptWorkbench.import.mergeSkip": "合并：同名跳过",
  "promptWorkbench.import.replace": "替换整个提示词库",
  "promptWorkbench.import.settings": "导入工作台设置",
  "promptWorkbench.import.optimizer": "导入优化提示词",
  "promptWorkbench.import.file": "提示词工作台备份",
  "promptWorkbench.import.choose": "选择文件",
  "promptWorkbench.import.noFile": "未选择文件",
  "promptWorkbench.export": "导出备份",
  "promptWorkbench.save": "保存提示词工作台",
  "promptWorkbench.status.saved": "提示词工作台已保存。",
  "promptWorkbench.status.exported": "提示词工作台备份已导出。",
  "promptWorkbench.status.imported": "已导入提示词备份：新增 {added}，更新 {updated}，跳过 {skipped}。",
  "promptWorkbench.status.importFailed": "提示词工作台导入失败。",
  "promptWorkbench.confirm.deletePrompt": "删除这个提示词？",
  "promptWorkbench.confirm.deleteFolder": "删除这个文件夹？其中的提示词会移动到无文件夹。",
  "promptWorkbench.confirm.replace": "替换整个本地提示词库？此操作无法撤销。",
  "promptWorkbench.action.optimize": "优化提示词",
  "promptWorkbench.aria.launcher": "打开提示词工作台",
  "promptWorkbench.content.library": "提示词库",
  "floatingNavigator.view.all": "全部问答",
  "floatingNavigator.view.favorites": "收藏",
  "floatingNavigator.action.addFavorite": "收藏此问答",
  "floatingNavigator.action.removeFavorite": "取消收藏",
  "floatingNavigator.action.jump": "跳转到此对话轮次",
  "floatingNavigator.empty.all": "暂未读取到对话轮次。",
  "floatingNavigator.empty.favorites": "还没有收藏的问答。",
  "floatingNavigator.unavailable": "原问答暂时无法定位。",
  "floatingNavigator.turn": "第 {number} 轮",
  "promptWorkbench.content.optimize": "优化提示词",
  "promptWorkbench.content.imagePrompt": "生图提示词",
  "promptWorkbench.content.variables": "变量",
  "promptWorkbench.content.manage": "管理提示词",
  "promptWorkbench.content.selectedText": "选中文本",
  "promptWorkbench.content.searchPrompts": "搜索提示词...",
  "promptWorkbench.content.searchHint": "置顶、最近使用与文件夹提示词会一起搜索。",
  "promptWorkbench.content.apply": "应用",
  "promptWorkbench.content.insert": "插入",
  "promptWorkbench.content.append": "追加",
  "promptWorkbench.content.replace": "替换",
  "promptWorkbench.content.chooseApply": "选择如何应用到当前输入。",
  "promptWorkbench.content.selectVariables": "请先选择带变量的提示词。",
  "promptWorkbench.content.missing": "缺失：{names}",
  "promptWorkbench.content.inputMissing": "未找到 ChatGPT 输入框。",
  "promptWorkbench.content.writeSomething": "请先写一些内容，再进行优化。",
  "promptWorkbench.content.optimizing": "正在优化当前输入...",
  "promptWorkbench.content.optimizedPrompt": "优化后的提示词",
  "promptWorkbench.content.strictPlanningSuggestions": "严格规划建议",
  "promptWorkbench.content.optimizationFailed": "AI 优化失败。",
  "promptWorkbench.content.errorDetails": "错误详情",
  "promptWorkbench.content.optimizeStage.readInput": "读取当前 ChatGPT 输入时失败。这通常是输入框或文本选区问题，不是 API Key 问题。",
  "promptWorkbench.content.optimizeStage.requestChatCompletion": "请求你配置的 AI 服务时失败。请结合下方详情检查服务商、模型、额度、域名权限或网络。",
  "promptWorkbench.content.optimizeStage.writeInput": "将优化后的提示词写回 ChatGPT 输入框时失败。页面可能刚刚重挂载了输入框。",
  "promptWorkbench.content.optimizeFailureHint": "下方原始错误已脱敏，可用于判断问题发生在读取输入、请求模型，还是写回输入阶段。",
  "promptWorkbench.content.openAiSettings": "打开 AI 设置",
  "promptWorkbench.content.copy": "复制",
  "promptWorkbench.content.imagePromptConcept": "以当前输入为基础，再选择下方生图约束。",
  "promptWorkbench.content.imagePromptCustom": "自定义选项...",
  "promptWorkbench.content.imagePromptAddCustom": "添加自定义选项",
  "promptWorkbench.content.imagePromptRandom": "随机",
  "promptWorkbench.content.imagePromptGenerate": "优化",
  "promptWorkbench.content.imagePromptSavePreset": "保存预设",
  "promptWorkbench.content.imagePromptPresetSaved": "生图提示词预设已保存。",
  "settings.defaultLayout": "默认布局",
  "layout.single": "单侧式",
  "layout.snake": "蛇形 / 顺序",
  "layout.radial": "环绕式",
  "layout.matrix": "矩阵式",
  "layout.twoSided": "两侧式",
  "relationship.related": "相关",
  "relationship.dependsOn": "依赖",
  "relationship.extends": "延伸",
  "relationship.supports": "支持",
  "relationship.contradicts": "反驳",
  "relationship.contrasts": "对比",
  "relationship.duplicates": "重复",
  "relationship.verifies": "验证",
  "relationship.references": "引用",
  "relationship.todo": "待办",
  "node.conversation": "对话",
  "node.note": "笔记",
  "node.turn": "轮次 {number}",
  "node.ai": "AI",
  "node.aiWorking": "AI...",
  "panel.nodesSelected": "已选择 {count} 个节点",
  "panel.organizeSelected": "将所选轮次整理为笔记或复习组。",
  "panel.nodeActions": "节点操作",
  "panel.nodeHint": "为所选节点添加标签、染色、折叠或标记重点。",
  "panel.linkTitle": "链接操作",
  "panel.headerTitle": "表头",
  "panel.headerHint": "双击表头文字即可编辑。",
  "field.type": "类型",
  "field.label": "标签",
  "action.close": "关闭",
  "action.mergeNodes": "合并节点",
  "action.collapseTopic": "折叠主题",
  "action.addTag": "添加标签",
  "action.colorNode": "染色",
  "action.collapseNode": "折叠",
  "action.expandNode": "展开",
  "action.open": "打开",
  "action.review": "复习",
  "action.done": "完成",
  "action.duplicateAsNote": "复制为笔记",
  "action.splitNode": "拆分节点",
  "action.selectAllTurns": "选择全部轮次",
  "action.important": "重要",
  "action.edgeWeight": "权重",
  "action.convertToNote": "转换为笔记",
  "action.deleteLink": "删除链接",
  "action.deleteHeader": "删除表头",
  "label.confidence": "置信度",
  "color.theme": "主题",
  "color.slate": "石板灰",
  "color.blue": "蓝色",
  "color.emerald": "翠绿色",
  "color.amber": "明黄色",
  "color.red": "红色",
  "color.violet": "紫色",
  "color.cyan": "青色",
  "color.rose": "深褐色",
  "status.nodesCollapsed": "已折叠所选节点。",
  "status.nodesExpanded": "已展开所选节点。",
  "status.nodesImportant": "已将所选节点标记为重要。",
  "status.nodesNormal": "已取消所选节点的重要标记。",
  "task.summarizeOne": "正在总结第 {current} 轮... 5%",
  "task.summarizeOneDone": "第 {current} 轮已总结。100%",
  "task.summarizeNote": "正在根据 {count} 个来源轮次总结 #AI 备注... 5%",
  "task.summarizeNoteDone": "#AI 备注已总结。100%",
  "task.summarizeAll": "正在总结 {total} 个轮次... 0%",
  "task.summarizeProgress": "AI 任务进度: {current}/{total}",
  "task.summarizeAllDone": "批量总结完成: 已更新 {total} 个轮次。100%",
  "task.summarizeFailed": "AI 总结失败。",
  "task.summarizeSkippedEdited": "已跳过 AI 总结，因为标题和摘要都已被手动编辑。",
  "task.summarizeNoteNeedsSource": "#AI 备注至少需要一个来源轮次后才能执行总结。",
  "task.autoSummarize": "正在自动总结 {total} 个默认节点... 0%",
  "task.autoSummarizeDone": "自动总结完成: 已更新 {total} 个节点。100%",
  "task.autoSummarizeFailed": "自动总结失败。",
  "task.suggestLinks": "正在请求 AI 建议语义链接... 15%",
  "task.suggestLinksRequesting": "正在等待 AI 链接建议... 45%",
  "task.suggestLinksFiltering": "正在筛选链接建议... 85%",
  "task.suggestLinksDone": "已有 {count} 条 AI 链接建议可供审阅。100%",
  "task.suggestLinksFailed": "AI 链接建议失败。",
  "task.analyzeTopics": "正在分析本地主题信号... 20%",
  "task.analyzeTopicsDone": "已有 {count} 条主题链接候选可供审阅。100%",
  "task.analyzeTopicsNone": "没有找到足够强的主题链接候选。100%",
  "task.analyzeTopicsFailed": "主题分析失败。",
  "task.translate": "正在将 ChatMap 界面翻译为 {language}... 10%",
  "task.translateDone": "已生成 {language} 翻译。100%",
  "settings.theme": "主题",
  "settings.theme.browser": "跟随浏览器",
  "settings.theme.day": "白天",
  "settings.theme.night": "夜晚",
  "settings.theme.eyeCare": "护眼",
  "settings.language": "语言",
  "settings.language.browser": "跟随浏览器",
  "settings.language.english": "English",
  "settings.language.chinese": "中文",
  "settings.languageHint": "内置中文和英文，默认跟随浏览器语言。",
  "settings.linkConnectionStyle": "连接样式",
  "settings.linkConnectionStyleCurved": "曲线",
  "settings.linkConnectionStyleAngled": "折线",
  "settings.defaultNodeSize": "默认节点大小设置",
  "settings.defaultNodeWidth": "节点长度",
  "settings.defaultNodeWidthHint": "默认 280 px，用于新生成节点和还原大小。",
  "settings.defaultNodeHeight": "节点宽度",
  "settings.defaultNodeHeightHint": "默认 220 px，用于新生成节点和还原大小。",
  "settings.defaultNodePromptRatio": "用户输入显示比例",
  "settings.defaultNodePromptRatioHint": "调节用户输入与 AI 回答的显示行数比例：0、25、50、75 或 100%。",
  "settings.customLanguage": "自定义语言",
  "settings.customLanguagePlaceholder": "西班牙语、日语、德语...",
  "settings.languageCode": "语言代码",
  "settings.languageCodePlaceholder": "fr-FR、ja-JP、de-DE...",
  "settings.generateTranslation": "用 AI 生成",
  "settings.generatingTranslation": "生成中...",
  "settings.importLanguagePack": "导入语言包",
  "settings.exportLanguagePack": "导出语言包",
  "settings.languagePackChooseFile": "选择文件",
  "settings.languagePackNoFile": "未选择文件",
  "settings.languagePackSelected": "已选择：{filename}",
  "settings.customTranslationHint": "AI 翻译只会发送 ChatMap 界面文案，不会发送你的对话内容。生成后的文案会保存在本地。",
  "settings.translationRepairHint": "如果模型返回的 JSON 格式不合法，ChatMap 可能额外调用一次 API 来修复语言包格式。",
  "settings.enableFloat": "默认启用浮窗导航",
  "settings.showLauncher": "在受支持 AI 页面显示 ChatMap 悬浮按钮",
  "settings.nodeColorRendering": "节点染色渲染",
  "settings.nodeColorRenderMode": "渲染方式",
  "settings.nodeColorRenderGradient": "渐变",
  "settings.nodeColorRenderSolid": "底色",
  "settings.nodeColorRenderStrength": "渲染程度",
  "settings.saveInterface": "保存界面设置",
  "settings.loadingInterface": "正在加载界面设置...",
  "settings.section.updates": "更新",
  "settings.section.updatesHint": "发布通知的预览控制",
  "settings.showUpdates": "有更新时显示提示",
  "settings.includePrerelease": "包含预发布版本",
  "settings.ignoredVersion": "忽略的版本",
  "settings.ignoredVersionPlaceholder": "v0.1.1",
  "settings.updateHint": "GitHub/解压安装无法由扩展静默更新。该功能接通后，更新提示会指向发布页或安装包。",
  "settings.saveUpdates": "保存更新设置",
  "settings.loadingUpdates": "正在加载更新设置...",
  "settings.translationSaved": "翻译已生成并保存。",
  "settings.translationNeedsName": "请先输入目标语言名称。",
  "settings.translationNeedsCode": "请先输入语言代码。",
  "settings.translationFailed": "AI 翻译失败。",
  "settings.languageImportDone": "已导入 {language}。缺失标签会回退英文：{count}。",
  "settings.languageImportFailed": "语言包导入失败。",
  "settings.languageImportConflict": "已有相同代码的自定义语言。是否替换？",
  "settings.languageImportCancelled": "已取消导入语言包。",
  "settings.languageExportNeedsCustom": "请先选择一个自定义语言再导出。",
  "settings.languageExportDone": "已导出 {language} 语言包。",
  "ai.title": "AI 服务",
  "ai.subtitle": "OpenAI 兼容的 Chat Completions",
  "ai.provider": "服务商",
  "ai.customCompatible": "自定义兼容接口",
  "ai.baseUrl": "Base URL",
  "ai.baseUrlPlaceholder": "https://api.example.com/v1",
  "ai.model": "模型",
  "ai.modelPlaceholder": "model-name",
  "ai.apiKey": "API Key",
  "ai.apiKeyPlaceholder": "保存在本地",
  "ai.apiKeyRawHint": "只粘贴 API Key 原文，不要包含 Bearer 前缀；ChatMap 会自动生成 Authorization 请求头。",
  "ai.maxTokens": "最大输出 tokens",
  "ai.maxTokensPlaceholder": "4000",
  "ai.maxTokensHint": "这是输出上限，不是模型上下文窗口。ChatMap 会为长回答总结使用较高但保守的预算；仅在 provider 和模型支持时再调高。",
  "ai.providerPresetLimit": "Provider 预设只是便利默认值；账号、地域、模型名、JSON mode 和上下文窗口可能随服务商变化。",
  "ai.providerNote.openai": "默认使用 gpt-5.4-nano，适合快速、低成本、长上下文的 OpenAI-compatible 任务。",
  "ai.providerNote.deepseek": "默认使用 deepseek-v4-flash。旧的 deepseek-chat 配置仍可保留，但不再作为新默认值。",
  "ai.providerNote.openrouter": "默认通过 OpenRouter 标准化接口使用 qwen/qwen3.5-flash-02-23。",
  "ai.providerNote.qwen": "默认通过 DashScope compatible mode 使用 qwen3.5-flash。",
  "ai.providerNote.kimi": "默认使用 kimi-k2.6。此预设不会强制发送 JSON mode。",
  "ai.providerNote.doubao": "默认使用豆包方舟兼容入口。部分 Volcano Ark 账号需要在 Model 字段填写 endpoint ID。",
  "ai.providerNote.zhipu": "默认通过 BigModel chat completions 使用 glm-4.7-flash。",
  "ai.providerNote.mistral": "默认使用 mistral-small-2603，并支持结构化 Chat Completions。",
  "ai.providerNote.geminiCompatible": "Gemini compatible 需要 Vertex 项目/地域 endpoint 和 OAuth Bearer token，不是普通静态 API Key。",
  "ai.providerNote.custom": "Custom 继续作为任意 OpenAI-compatible chat completions endpoint 的兜底。",
  "ai.privacy": "API Key 会保存在浏览器扩展存储中。只有在你运行 AI 功能或启用自动总结时，ChatMap 才会发送对话文本。",
  "ai.autoSummarize": "自动总结新的默认节点",
  "ai.status.local": "设置保存在本地。AI 功能会把选中的对话文本发送给你配置的 provider。",
  "ai.status.saved": "已保存。",
  "ai.status.aiSaved": "AI 设置已保存。",
  "ai.status.testing": "正在测试连接...",
  "ai.status.connectionSaved": "连接成功，设置已保存。",
  "ai.status.connectionSavedGlobal": "AI 连接成功，设置已保存。",
  "ai.status.failed": "连接测试失败。",
  "ai.save": "保存",
  "ai.test": "测试连接",
  "ai.testing": "测试中..."
};
export const BUILT_IN_TRANSLATIONS: Record<BuiltInLanguage, TranslationMap> = {
  en: EN_TRANSLATIONS,
  zh: ZH_TRANSLATIONS
};
